name: Developer_Branch_CI
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo npm test #for nodejs test just this command if any unit tests define will run here npm test

      - name: Integration Tests
        run: echo Integration Tests

      - name: Code Quality
        run:  sonar-scanner -Dsonar.host.url=http://sonarqube-int.jyothsnashrey.online:9000 -Dsonar.login={{ secret.SONAR_USER }} -Dsonar.password={{ secret.SONAR_PASS }} -Dsonar.projectKey=expense-backend






