name: Release_Tags
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SAST Scans
        run: echo SAST Scans

      - name: SCA Scans
        run: echo SCA Scans

      - name: Detect Secrets in Source Code
        run: echo Detect Secrets in Source Code

      - name: Produce Artifact
        env:
            service_name: ${{ inputs.service_name }}

        run: |  #pipe symbol to run multiple commands
          npm install  #this is used to get all the  dependencies
          zip -r ${service_name}-${GITHUB_REF_NAME}.zip * -x .github
          curl -v -X put -u  admin:Admin123 -T ${service_name}-${GITHUB_REF_NAME}.zip http://artifactory-int.jyothsnashrey.online:8081/artifactory/${service_name}/${service_name}-${GITHUB_REF_NAME}.zip
        
        

        # you can * also but it will also keep .github folder which is unnecessary so we will ignore that directory by -x



